title: Vladi Skokov's group  
description: Website of Vladi Skokov's group 
theme: just-the-docs


favicon_ico: "/assets/images/favicon.ico"

source 'https://rubygems.org'

gem "jekyll", "~> 4.3.2" # installed by `gem jekyll`
# gem "webrick"        # required when using Ruby >= 3 and Jekyll <= 4.2.2

gem "just-the-docs", "0.6.2" # pinned to the current release
# gem "just-the-docs"        # always download the latest release

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"


  #color_scheme: dark
color_scheme: light
